#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : sg3_utils
Version  : 1.48
Release  : 16
URL      : https://sg.danny.cz/sg/p/sg3_utils-1.48.tar.xz
Source0  : https://sg.danny.cz/sg/p/sg3_utils-1.48.tar.xz
Summary  : Utilities for devices that use SCSI command sets
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0+
Requires: sg3_utils-bin = %{version}-%{release}
Requires: sg3_utils-lib = %{version}-%{release}
Requires: sg3_utils-license = %{version}-%{release}
Requires: sg3_utils-man = %{version}-%{release}
BuildRequires : buildreq-configure
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Collection of Linux utilities for devices that use the SCSI command set.
Includes utilities to copy data based on "dd" syntax and semantics (called
sg_dd, sgp_dd and sgm_dd); check INQUIRY data and VPD pages (sg_inq); check
mode and log pages (sginfo, sg_modes and sg_logs); spin up and down
disks (sg_start); do self tests (sg_senddiag); and various other functions.
See the README, ChangeLog and COVERAGE files. Requires the linux kernel 2.4
series or later. In the 2.4 series SCSI generic device names (e.g. /dev/sg0)
must be used. In the 2.6 series and later other device names may be used as
well (e.g. /dev/sda). Also some support for NVMe devices, especially with
sg_ses on NVMe enclosures.

Warning: Some of these tools access the internals of your system
and the incorrect usage of them may render your system inoperable.

%package bin
Summary: bin components for the sg3_utils package.
Group: Binaries
Requires: sg3_utils-license = %{version}-%{release}

%description bin
bin components for the sg3_utils package.


%package dev
Summary: dev components for the sg3_utils package.
Group: Development
Requires: sg3_utils-lib = %{version}-%{release}
Requires: sg3_utils-bin = %{version}-%{release}
Provides: sg3_utils-devel = %{version}-%{release}
Requires: sg3_utils = %{version}-%{release}

%description dev
dev components for the sg3_utils package.


%package lib
Summary: lib components for the sg3_utils package.
Group: Libraries
Requires: sg3_utils-license = %{version}-%{release}

%description lib
lib components for the sg3_utils package.


%package license
Summary: license components for the sg3_utils package.
Group: Default

%description license
license components for the sg3_utils package.


%package man
Summary: man components for the sg3_utils package.
Group: Default

%description man
man components for the sg3_utils package.


%prep
%setup -q -n sg3_utils-1.48
cd %{_builddir}/sg3_utils-1.48
pushd ..
cp -a sg3_utils-1.48 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1691086011
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1691086011
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sg3_utils
cp %{_builddir}/sg3_utils-%{version}/debian/copyright %{buildroot}/usr/share/package-licenses/sg3_utils/f2d373f60508c38ab50afee7e28a502a2863805e || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/sg_write_buffer
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/sg_bg_ctl
/V3/usr/bin/sg_compare_and_write
/V3/usr/bin/sg_copy_results
/V3/usr/bin/sg_dd
/V3/usr/bin/sg_decode_sense
/V3/usr/bin/sg_emc_trespass
/V3/usr/bin/sg_format
/V3/usr/bin/sg_get_config
/V3/usr/bin/sg_get_elem_status
/V3/usr/bin/sg_get_lba_status
/V3/usr/bin/sg_ident
/V3/usr/bin/sg_inq
/V3/usr/bin/sg_logs
/V3/usr/bin/sg_luns
/V3/usr/bin/sg_map
/V3/usr/bin/sg_map26
/V3/usr/bin/sg_modes
/V3/usr/bin/sg_opcodes
/V3/usr/bin/sg_persist
/V3/usr/bin/sg_prevent
/V3/usr/bin/sg_raw
/V3/usr/bin/sg_rbuf
/V3/usr/bin/sg_rdac
/V3/usr/bin/sg_read
/V3/usr/bin/sg_read_attr
/V3/usr/bin/sg_read_block_limits
/V3/usr/bin/sg_read_buffer
/V3/usr/bin/sg_read_long
/V3/usr/bin/sg_readcap
/V3/usr/bin/sg_reassign
/V3/usr/bin/sg_referrals
/V3/usr/bin/sg_rem_rest_elem
/V3/usr/bin/sg_rep_density
/V3/usr/bin/sg_rep_pip
/V3/usr/bin/sg_rep_zones
/V3/usr/bin/sg_requests
/V3/usr/bin/sg_reset
/V3/usr/bin/sg_reset_wp
/V3/usr/bin/sg_rmsn
/V3/usr/bin/sg_rtpg
/V3/usr/bin/sg_safte
/V3/usr/bin/sg_sanitize
/V3/usr/bin/sg_sat_datetime
/V3/usr/bin/sg_sat_identify
/V3/usr/bin/sg_sat_phy_event
/V3/usr/bin/sg_sat_read_gplog
/V3/usr/bin/sg_sat_set_features
/V3/usr/bin/sg_scan
/V3/usr/bin/sg_seek
/V3/usr/bin/sg_senddiag
/V3/usr/bin/sg_ses
/V3/usr/bin/sg_ses_microcode
/V3/usr/bin/sg_start
/V3/usr/bin/sg_stpg
/V3/usr/bin/sg_stream_ctl
/V3/usr/bin/sg_sync
/V3/usr/bin/sg_test_rwbuf
/V3/usr/bin/sg_timestamp
/V3/usr/bin/sg_turs
/V3/usr/bin/sg_unmap
/V3/usr/bin/sg_verify
/V3/usr/bin/sg_vpd
/V3/usr/bin/sg_wr_mode
/V3/usr/bin/sg_write_attr
/V3/usr/bin/sg_write_long
/V3/usr/bin/sg_write_same
/V3/usr/bin/sg_write_verify
/V3/usr/bin/sg_write_x
/V3/usr/bin/sg_xcopy
/V3/usr/bin/sg_z_act_query
/V3/usr/bin/sg_zone
/V3/usr/bin/sginfo
/V3/usr/bin/sgm_dd
/V3/usr/bin/sgp_dd
/usr/bin/rescan-scsi-bus.sh
/usr/bin/scsi_logging_level
/usr/bin/scsi_mandat
/usr/bin/scsi_readcap
/usr/bin/scsi_ready
/usr/bin/scsi_satl
/usr/bin/scsi_start
/usr/bin/scsi_stop
/usr/bin/scsi_temperature
/usr/bin/sg_bg_ctl
/usr/bin/sg_compare_and_write
/usr/bin/sg_copy_results
/usr/bin/sg_dd
/usr/bin/sg_decode_sense
/usr/bin/sg_emc_trespass
/usr/bin/sg_format
/usr/bin/sg_get_config
/usr/bin/sg_get_elem_status
/usr/bin/sg_get_lba_status
/usr/bin/sg_ident
/usr/bin/sg_inq
/usr/bin/sg_logs
/usr/bin/sg_luns
/usr/bin/sg_map
/usr/bin/sg_map26
/usr/bin/sg_modes
/usr/bin/sg_opcodes
/usr/bin/sg_persist
/usr/bin/sg_prevent
/usr/bin/sg_raw
/usr/bin/sg_rbuf
/usr/bin/sg_rdac
/usr/bin/sg_read
/usr/bin/sg_read_attr
/usr/bin/sg_read_block_limits
/usr/bin/sg_read_buffer
/usr/bin/sg_read_long
/usr/bin/sg_readcap
/usr/bin/sg_reassign
/usr/bin/sg_referrals
/usr/bin/sg_rem_rest_elem
/usr/bin/sg_rep_density
/usr/bin/sg_rep_pip
/usr/bin/sg_rep_zones
/usr/bin/sg_requests
/usr/bin/sg_reset
/usr/bin/sg_reset_wp
/usr/bin/sg_rmsn
/usr/bin/sg_rtpg
/usr/bin/sg_safte
/usr/bin/sg_sanitize
/usr/bin/sg_sat_datetime
/usr/bin/sg_sat_identify
/usr/bin/sg_sat_phy_event
/usr/bin/sg_sat_read_gplog
/usr/bin/sg_sat_set_features
/usr/bin/sg_scan
/usr/bin/sg_seek
/usr/bin/sg_senddiag
/usr/bin/sg_ses
/usr/bin/sg_ses_microcode
/usr/bin/sg_start
/usr/bin/sg_stpg
/usr/bin/sg_stream_ctl
/usr/bin/sg_sync
/usr/bin/sg_test_rwbuf
/usr/bin/sg_timestamp
/usr/bin/sg_turs
/usr/bin/sg_unmap
/usr/bin/sg_verify
/usr/bin/sg_vpd
/usr/bin/sg_wr_mode
/usr/bin/sg_write_attr
/usr/bin/sg_write_long
/usr/bin/sg_write_same
/usr/bin/sg_write_verify
/usr/bin/sg_write_x
/usr/bin/sg_xcopy
/usr/bin/sg_z_act_query
/usr/bin/sg_zone
/usr/bin/sginfo
/usr/bin/sgm_dd
/usr/bin/sgp_dd

%files dev
%defattr(-,root,root,-)
/usr/include/scsi/sg_cmds.h
/usr/include/scsi/sg_cmds_basic.h
/usr/include/scsi/sg_cmds_extra.h
/usr/include/scsi/sg_cmds_mmc.h
/usr/include/scsi/sg_io_linux.h
/usr/include/scsi/sg_json.h
/usr/include/scsi/sg_json_sg_lib.h
/usr/include/scsi/sg_lib.h
/usr/include/scsi/sg_lib_data.h
/usr/include/scsi/sg_lib_names.h
/usr/include/scsi/sg_linux_inc.h
/usr/include/scsi/sg_pr2serr.h
/usr/include/scsi/sg_pt.h
/usr/include/scsi/sg_pt_linux.h
/usr/include/scsi/sg_pt_nvme.h
/usr/include/scsi/sg_unaligned.h
/usr/lib64/libsgutils2.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsgutils2-1.48.so.2.0.0
/usr/lib64/libsgutils2-1.48.so.2
/usr/lib64/libsgutils2-1.48.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sg3_utils/f2d373f60508c38ab50afee7e28a502a2863805e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/rescan-scsi-bus.sh.8
/usr/share/man/man8/scsi_logging_level.8
/usr/share/man/man8/scsi_mandat.8
/usr/share/man/man8/scsi_readcap.8
/usr/share/man/man8/scsi_ready.8
/usr/share/man/man8/scsi_satl.8
/usr/share/man/man8/scsi_start.8
/usr/share/man/man8/scsi_stop.8
/usr/share/man/man8/scsi_temperature.8
/usr/share/man/man8/sg3_utils.8
/usr/share/man/man8/sg3_utils_json.8
/usr/share/man/man8/sg_bg_ctl.8
/usr/share/man/man8/sg_compare_and_write.8
/usr/share/man/man8/sg_copy_results.8
/usr/share/man/man8/sg_dd.8
/usr/share/man/man8/sg_decode_sense.8
/usr/share/man/man8/sg_emc_trespass.8
/usr/share/man/man8/sg_format.8
/usr/share/man/man8/sg_get_config.8
/usr/share/man/man8/sg_get_elem_status.8
/usr/share/man/man8/sg_get_lba_status.8
/usr/share/man/man8/sg_ident.8
/usr/share/man/man8/sg_inq.8
/usr/share/man/man8/sg_logs.8
/usr/share/man/man8/sg_luns.8
/usr/share/man/man8/sg_map.8
/usr/share/man/man8/sg_map26.8
/usr/share/man/man8/sg_modes.8
/usr/share/man/man8/sg_opcodes.8
/usr/share/man/man8/sg_persist.8
/usr/share/man/man8/sg_prevent.8
/usr/share/man/man8/sg_raw.8
/usr/share/man/man8/sg_rbuf.8
/usr/share/man/man8/sg_rdac.8
/usr/share/man/man8/sg_read.8
/usr/share/man/man8/sg_read_attr.8
/usr/share/man/man8/sg_read_block_limits.8
/usr/share/man/man8/sg_read_buffer.8
/usr/share/man/man8/sg_read_long.8
/usr/share/man/man8/sg_readcap.8
/usr/share/man/man8/sg_reassign.8
/usr/share/man/man8/sg_referrals.8
/usr/share/man/man8/sg_rem_rest_elem.8
/usr/share/man/man8/sg_rep_density.8
/usr/share/man/man8/sg_rep_pip.8
/usr/share/man/man8/sg_rep_zones.8
/usr/share/man/man8/sg_requests.8
/usr/share/man/man8/sg_reset.8
/usr/share/man/man8/sg_reset_wp.8
/usr/share/man/man8/sg_rmsn.8
/usr/share/man/man8/sg_rtpg.8
/usr/share/man/man8/sg_safte.8
/usr/share/man/man8/sg_sanitize.8
/usr/share/man/man8/sg_sat_datetime.8
/usr/share/man/man8/sg_sat_identify.8
/usr/share/man/man8/sg_sat_phy_event.8
/usr/share/man/man8/sg_sat_read_gplog.8
/usr/share/man/man8/sg_sat_set_features.8
/usr/share/man/man8/sg_scan.8
/usr/share/man/man8/sg_seek.8
/usr/share/man/man8/sg_senddiag.8
/usr/share/man/man8/sg_ses.8
/usr/share/man/man8/sg_ses_microcode.8
/usr/share/man/man8/sg_start.8
/usr/share/man/man8/sg_stpg.8
/usr/share/man/man8/sg_stream_ctl.8
/usr/share/man/man8/sg_sync.8
/usr/share/man/man8/sg_test_rwbuf.8
/usr/share/man/man8/sg_timestamp.8
/usr/share/man/man8/sg_turs.8
/usr/share/man/man8/sg_unmap.8
/usr/share/man/man8/sg_verify.8
/usr/share/man/man8/sg_vpd.8
/usr/share/man/man8/sg_wr_mode.8
/usr/share/man/man8/sg_write_attr.8
/usr/share/man/man8/sg_write_buffer.8
/usr/share/man/man8/sg_write_long.8
/usr/share/man/man8/sg_write_same.8
/usr/share/man/man8/sg_write_verify.8
/usr/share/man/man8/sg_write_x.8
/usr/share/man/man8/sg_xcopy.8
/usr/share/man/man8/sg_z_act_query.8
/usr/share/man/man8/sg_zone.8
/usr/share/man/man8/sginfo.8
/usr/share/man/man8/sgm_dd.8
/usr/share/man/man8/sgp_dd.8
